language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registration_numbers

node_js:  
  - "12"

before_script:
  - psql -c 'create database  registration_numbers;' -U postgres
  - psql -U postgres -d registration_numbers -a -f reg.sql

services:
  - postgresql