language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/reg_test

node_js:  
  - "12"

before_script:
  - psql -c 'create database  reg_test;' -U postgres
  - psql -U postgres -d reg_test -a -f reg.sql

services:
  - postgresql